### ISSUE TITLE
Chrome blocking filesystem tarball download due to requesting http resource from https page.

### ISSUE THREAD

**Issue by benjamincburns** [s-macke/jor1k#106]
Per title, filesystem tarball can't be restored on chrome from github demo page.

    Mixed Content: The page at 'https://s-macke.github.io/jor1k/demos/main.html?user=ss1BsNOW9s' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://jor1k.com/sync/tarballs/ss1BsNOW9s.tar.bz2'. This request has been blocked; the content must be served over HTTPS.

![image](https://cloud.githubusercontent.com/assets/803016/10205454/ccb5d324-681d-11e5-81f6-c957e81c933d.png)

**Comment by s-macke** [comment]
Yes, I know. The same problem we had with your websocket connection. Since Google automatically changed to https if availabe everyone receives the encrypted page. Hence, the connection to another server must be encrypted as well. Actually my plan is to wait for the "Let's encrypt" service from Mozilla to get a cheap certificate for this.
At the moment you have to change to the non-encrypted jor1k website for this "cloud" service.

**Comment by benjamincburns** [comment]
I'd be happy to spring for a 1 year cert from my provider if you'd like.

**Comment by s-macke** [comment]
Yeah, that would be great :)
Have never configured my webserver for https. What do you need?

**Comment by benjamincburns** [comment]
I'm not 100% certain yet. I'll likely just be able to send you a `.crt` to install. I'll have a look tomorrow and get in touch.

**Comment by s-macke** [comment]
https://github.com/s-macke/jor1k/commit/e969123f6a79fd1aff03e690e13fdabefbc7a003
Fixed
